title: Write the Docs Boise
author: ""
description: >
  Write The Docs Boise is a meetup for Treasure Valley technical writers,
  software developers, content strategists, and editors.

header_pages:
  - about.md

# Allow future dated posts
future: true

theme: minima
plugins:
  - jemoji
  - jekyll-mentions
exclude:
  - Gemfile
  - vendor
minima:
  date_format: "%F"
